os: osx
language: objective-c
osx_image: xcode11


jobs:
  include:
    - name: Darwin 
      env:
        - WORKSPACE='KisMac2.xcworkspace'
        - MACOS_SCHEME='KisMac2'
        - MACOS_DESTINATION='platform=OS X'
      before_install:
        - git submodule update --init --recursive
      script:
        - set -o pipefail
        - xcodebuild clean build -workspace "$WORKSPACE" -scheme "$MACOS_SCHEME" -destination "$MACOS_DESTINATION"

branches:
  only:
    - master
