name: BuildCI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=OS X']
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: Start xcodebuild build
      run: set -o pipefail && xcodebuild clean build -workspace "${PROJ_WORKSPACE}" -scheme "${PROJ_SCHEME}" -destination "${PROJ_DESTINATION}"
      env: 
        PROJ_DESTINATION: ${{ matrix.destination }}
        PROJ_WORKSPACE: 'KisMac2.xcworkspace'
        PROJ_SCHEME: 'KisMac2'
